---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: ucrmp-platform-secrets
  namespace: ucrmp-dev
spec:
  encryptedData:
    jwtSecret: AgAfF2u95CCqiuWDR2iZBS+VdTphops20CEVWRF69A4hOe50iLqUikNLpdO+dUBRc4JVGTss3a4voDpBezLVc+ZDr2caTgrgVlI8hdVGZsoZKXbDFP+zo8CEykl3d4EbCTfHKdnwcSwJdYrkA7YQ3aKViAJ1VloOqxJRg8nuc5aenv+aarBDvCJcNyC+E6l4bGpPjYKj/CYQoDRLZ9Xm3dC0Vccs86co+WSe+W1jjIA8SSjGjln0fdpWXO85HETssMLK97LOuTkremxNZPKgPqFoU/RGjPZX9IbixrsOa6DGzEgCr7EL3PhY0fYoiLTwemIZauCirjT4bDXfQ5kSbAnuR2Jn3bYnmDJCnPbHMswiStFsJN0mTUX78zzJ20Jv9d5rVJwI6do6cC5Q/EtpilbvnjJ72T18bAPylOIFXxBFv/XLlMq6eTb0h+kmKgEemWmzxVroELgV+eJwg5UjVLAO2z9tj/0YAg0ct6oN1KvzB+AVsr5GevmPH87tC+kOOPDjOoiXryaUtDNsxdWTEiWo9gS1NYtVCwwBUPP/kLCm48gonUk9yLI9ol35/WfQj+UIcOJoEuZyg+Ng0KbMDpz8dRk+4DjMbtHTg8tKqtWK+b1S0O6HK8tK4Z+x7ClNBo3NxYcWD8qgCQOkkK6qseKjepXk6DIU3TrcZjbvmq4CYgBzga6RhTeOrwvdbozsKTrhd8tgMzaE7gh0kc5UOFx1dX1inR2JC+2ULiIRe/qyESqd8mWUmy8aCC5uv4AFDsXDMdSfdYzMxJcL3ZcgqzTNsEizCEOE+P23/THnbSFEbbDB4HGloOuf1k+N1Q==
    mysqlRoot: AgAREUK73pV5FtjSgLA/pXWUFUONSdpdNmPSiZJmfwVJQnmpqhNN010ipPrPOU47HD/hqdHubxnJxEjZxrkaA+dtqA8CWRhxjV7zz+kqMxj/ZmJLdJzWrtzmmNrfVj6t8smUbvQwi6t6SVag50r5nAp4FrJWwMRohpTLYriuvNDMmWbI9UcoSxoyuWkajnKNCcG4h+M9Ws5yjKX6WY0v/sisQECnXnWK2nmXJER2um/eztaWt345h9DRx2NKmqnMQPS/yWdPHJ/AxNCscOYenjB5A7X4GbhadyQfaVj+Ad9pmd25df3Ya9/6eBUDNgUPn5jZq8uSDbdSnrpYS9ZcG6I/SCOMZJHdGSD5Jk1pbR9o+yucsNkrNYZB4sesbg18A6qqF7tlHmkDe63KSph2pUuVivDvrZ98hszeRYIIqVaUmRKsgwm0gah0XyqxKsDgV0d4Qh59L8C8N/b6WddX+Qz4OJoZtjS5MoJg25mID0QOiPJumjLEIfRLl+yY9AXLVx6NDXigjsDg2oTrP7cVgq2KXH2qZUIXPww92nV1XG+aDZ+NzHZVkDjlBxp1qhzgtxk08rnEOIk/yAd4XPIasqnmZcmjo71tpYVYklYawa/9tION1YV/1+3p6MBu/F1Cxse4VbGj7Hi4X9UNnTRZ2BScdtWUTHEYNBbHI/B+7HgNuO/WdyIOVfDUiifJFzB01yjp1f3i
  template:
    metadata:
      name: ucrmp-platform-secrets
      namespace: ucrmp-dev
    type: Opaque
