---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: ucrmp-platform-secrets
  namespace: ucrmp-dev
spec:
  encryptedData:
    jwtSecret: AgCaN6qE8TW/y6TIKrb8Q6CUfWWcKRG+4VOI+feqaF3n+3hVMBfGJqmc/sl/AKNMosC4MTPpUE42tvDSXDuUBSb1DBRuiu5Ng6yCvNFnX0UgYDsCbP8Fuu5Q4WwddjYfOE345PbqwQRPS9H4uuNTFFZiqfzhu3uohzYonMoB8pRClriavFPCStF72oQZnvevVrB1mSo5nKWFhDqOprdB+53yZfoF53xY24QkMUqzrdrhGmlXokUtBY05LMlQn6dF1JPaoD44NKYnqR5cHNv+EeRbdhp/0OipIQj+1cv3AlBpCdkfe/pmdxtqf6CZm5D0lWfNove260sTi5QW+pT7E8Hfanfoumio2HjWIjZ9GcfcdoqHsNFENUwleuxjJYWyDSKxcXFPTH8mBuxWBmJN7rXsaXXhLXkdg9BfjZWhsXpoPNtcTLXNA+e5iGwY9GtFi6+zZ7JTJkIExeBamveSV48ZkwmxtUSCxF3ACeCTKEnprRlzEJsyLdh6VZ/ZdvzDyzzhqcqgzNdnBLLwqKY1xik/r2NGDHRwRcicXWQSytWKIpzHqlurh/gssQtBY/TZIVglyA2nN/2Tiq09nV9qWmoN8fIwMznwUpNhNpmG6FVapr/I/oMM6sGxzG3bjiwEaXevz1kw55r3mNgcFGRU4eKF49CfHBAwz9XUcIJiKNBOtVt7b0h9DopWc+ljQ6dx6RNa/K2Tf26tLY8c0Imo1tpMgeESMHK3DSVLaYVFjnsyoPcjY3wejM0Q/PIP4KmPnRMkog8e7np1cKznXLIKC1m463LXS9qcWnuMY6dHg8zQMdNQRd0z1Zw/4DWEgJ/tElvgnRbs1bldUJIBk4g=
    mysqlRoot: AgBcAn7+I5/3RlpKOWh5ZI2LnPPkyXIoQMMEt8FmHwGwJFsc6GCh+nNm7SLrRhO7fyY5d7yq3QOEWCyEHW4s/BGlTsKwJ+nQW/YbEybxStPHSsYSTm6yVqqNaLojVazW3Ii8v9GgA+VXCArS9itSrdeKNqhAjh++c66De8YQ4tpfU1kyRu4pN3p1P6n9ZMmbIjtQvZ8mf1a1NEeh+v7vaD3vCAWeKyO7Ha2XL1Z4NKyug2nbKaeqFpgXc5RMrd2MoABAHFZ0p9LolWgUTydAS4mE3TcYw1xkqdVMJkS8xOCdM6SdvsQRJayRjn8DST8Nf0v3rU/uA5EaX9dXMEJKv9tXHvPpimIGWwN/QJ1h3H134B5Ky3kh8ize2DQnwRBkGoLDc/pPTuILmKbv/4zXewIvxX8feZY3zDBTNFe9gtjTaVH+mYGivj16IPT33c2uzlR6zSaEGU7byfp4OaFFWMZED7McLIfNqtvUS6MV3+0LAuznPZ1mG2xnmzCVzYAZlbmAuP/NmnlpDJ+2VLozfRGu/gy2XTlU4llsSqOrDIkikuqOlrU5rCN0UlSKacDxiGXAbkUkyVbYZG5jCP4CnMaUvdjayEwbj06fLE9ucyQIetOyLCEdG7kRwsvV7SniYXtj8cjhvLAx5Y9LrU3faVck0/7XWmHvHIr9+iKUVcggBKLzAh3smgfLqU9JI6p+tMqgfp5A
  template:
    metadata:
      name: ucrmp-platform-secrets
      namespace: ucrmp-dev
    type: Opaque
