---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: ucrmp-platform-secrets
  namespace: ucrmp-dev
spec:
  encryptedData:
    jwtSecret: AgClBRIGck1n/JEwo/qaYEqyBH9HNwLaHlf1AtJfiChwDEZMrgUdBGderIou6Uye9Kqi71Veu2O+8mQFlflLX1+eVov1FFzxqK6qY9g252t7+u+s/w5Mtoxthalwo3cEL5z2sFuWG+Uwsx5f+5OkvNEjGhhSCoU+uTYgA3py/l+tDHU9DWHq7ESreb8mP7XdgUGue2dz7DMQe0vGIjLV7wW8/cSdHv3ruZ8jp2c2WbGpWt3AVc4rGtfNN0gdrELTy2r6+t+qh4kj8N4UxnL52y8PnaiWi9pgbpZIelJ7oFA3lSO5JW5oE5JirHmfYyUreoXuTKaxjRh1iBeBUIUn1mHu+Hpg3jZAyfAblz7vzXbcu/QyojzlAWMkI4PLlDL5SCRxdmR40kTKVQ+58k+dargOOTi1ivtomqqlO5+aWPzVGFmojDmR+lO7YsSnHVH8DCi47VK3WH1AaT1j8NpHvT/xPcjxcVLtPtNzhrqy8x25u7x3VCrkV7pP1j6/plGwr9TRf8OdfNLXuEpTpbpvJq760yvqqf1aIKWHKTDPOj1u58Ul+Wxnv3hDUY+Z/f/GMVF0ryoK6AxV4CUA2cHtbtvW9MLKX7KgvmIWHvH2WFTISANl2ZaTE6fOKr2J0Dc+Jc2Tkx+CywkAyeCUDrvh8giEQp13UEvqfrcP8Id1aP9eMGDXNGI/LwOt9/LN2gNOxT03V5kDlLa69uRG8p5pbOPIi6KlVlbyn0622XtNRGNjC54QweEO53t6FswcTq8wiU8ypOXNyLRr9A9X+l9JgtpPWGQCrjyNfCzKvjGWgR/Pklw0iLLn9fSaO11oqAcTCaDzUlw4Lh+r4kejrDA=
    mysqlRoot: AgB6Tr9X3Hu8ttU/ykF6Ozr3HxEpnC+0uCHrTuwqmopmFvG/GsFseblnzx65vSq3kq1ViN3tPeWBjuZu1OMPfCaAW+G6SvPmI1pCpgGS4k+1o3yv3m7CV14BhR3CgordNqRYygo9MSIML3s0nN0MmYroaDZDv/6qleaIsOYV5/NQjQsmS4uQtLeTdJrgs1s7o95V5dC9NFPwqBzLU5PdMyQi6Zm+SYP9rYi3JVSp/zVyeSbCCsb8kZ2mvmw5aSoH/XEVD+EfWaBLsILcbhGAVJ0UWSIYRr2TTpK7u2xNuuAIgZ+IcTIwYax7+sDKUNuKKiLdJ1ZNyhu7TpKnM4WVlVLXJZKesi7wRvKRkDEsCCk1xCUJxGB2A4BeyXj/YyE/L2ogLp9pa1PWdBFBdM7mpi1Ck8Cnlw7+FyxG7iIWpaMEjmnNUei1c1Buv+nV9pDrBTikBnvZVNu0w2+RzuzSX9TumD76yrxJ6cPt+uNzk8RQCZfEdEKoWisQaNUccQkOez8KrmrsELAqmE2H/cdiWvnz/FvX9c6dx+S/AP3wl+OQZf3TQ+laZO+BW5VVrrApvO/zWff5C9QsvX65YVa8lo7weGDI7z/KT22VpIZ5u/jXmrafBxg109tfqLA3ZansFH/oAJvSSaJ57tw11Erso56ThbLi+Ib9LAnnmcpbImSpX3g9A7+8PAch65jwoV1z3eUPrWD3
  template:
    metadata:
      name: ucrmp-platform-secrets
      namespace: ucrmp-dev
    type: Opaque
